AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/*
    - gemfiles/*
    - spec/**/*

Metrics/LineLength:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
