language: ruby
cache: bundler
sudo: false
rvm:
  - 2.6.0-rc2
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - jruby-9.2.0.0
before_install:
  - gem update --system
  - gem install bundler --no-document
gemfile:
  - gemfiles/rails_4.2.10.gemfile
  - gemfiles/rails_5.0.7.gemfile
  - gemfiles/rails_5.1.6.gemfile
  - gemfiles/rails_5.2.0.gemfile
