dist: trusty
language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - jruby-9.2.0.0
before_install:
  - gem update --system
  - gem install bundler
gemfile:
  - gemfiles/rails_4.2.10.gemfile
  - gemfiles/rails_5.0.7.gemfile
  - gemfiles/rails_5.1.6.gemfile
  - gemfiles/rails_5.2.0.gemfile
