language: ruby
cache: bundler
sudo: false
rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - 2.4.10
  - 2.3.8
  - ruby-head
  - jruby-9.2.13.0
gemfile:
  - gemfiles/rails_4.2.10.gemfile
  - gemfiles/rails_5.0.7.gemfile
  - gemfiles/rails_5.1.6.gemfile
  - gemfiles/rails_5.2.0.gemfile
