language: ruby
cache: bundler
sudo: false
rvm:
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - 2.3.8
  - ruby-head
  - jruby-9.2.5.0
gemfile:
  - gemfiles/rails_4.2.10.gemfile
  - gemfiles/rails_5.0.7.gemfile
  - gemfiles/rails_5.1.6.gemfile
  - gemfiles/rails_5.2.0.gemfile
