---
os: linux
dist: xenial

language: ruby
cache: bundler
rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - ruby-head
  - jruby-9.2.13.0

gemfile:
  - gemfiles/rails_5.1.7.gemfile
  - gemfiles/rails_5.2.4.gemfile
  - gemfiles/rails_6.0.3.gemfile
